name: hp_mobile_waisaka
description: "Waisaka Mobile Property - Mobile application for Waisaka Property."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Routing
  go_router: ^16.2.0

  # Networking
  dio: ^5.3.3
  http: ^1.1.0

  # Local Storage
  path_provider: ^2.1.4
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  device_info_plus: ^10.1.0
  flutter_secure_storage: ^8.0.0

  # Voice Command & AI
  google_generative_ai: ^0.4.7
  speech_to_text: ^7.3.0
  record: ^6.1.1       

  # UI & Utilities
  carousel_slider: ^5.1.1
  image_picker: ^1.0.4
  intl: ^0.20.2
  url_launcher: ^6.2.1
  google_maps_flutter: ^2.9.0
  flutter_html: ^3.0.0-beta.2
  crypto: ^3.0.3
  share_plus: ^7.2.1
  provider: ^6.1.1
  flutter_quill: ^11.4.2
  font_awesome_flutter: ^10.7.0
  permission_handler: ^11.3.1

  # Dependency Injection
  get_it: ^8.2.0

  # Icons
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.2
  flutter_tts: ^4.2.3
  google_fonts: ^6.3.0
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.10.0 

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
